name: Build and Release Electron App

on:
  push:
    branches: [ main ]

jobs:
  build:
    runs-on: windows-latest

    steps:
      # Step 1 — Checkout repo
      - uses: actions/checkout@v4

      # Step 2 — Setup Node.js
      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 20

      # Step 3 — Install dependencies
      - name: Install dependencies
        run: npm install

      # Step 4 — Build Electron app
      - name: Build app
        run: npm run dist
        env:
          GH_TOKEN: ${{ secrets.GH_TOKEN }}
          CSC_LINK: ""  # skip code-signing

      # Step 5 — Create or update a single "latest" Release
      - name: Create/Update Latest Release
        uses: softprops/action-gh-release@v1
        with:
          tag_name: latest
        env:
          GITHUB_TOKEN: ${{ secrets.GH_TOKEN }}

      # Step 6 — Upload .exe to the "latest" Release
      - name: Upload Release Asset
        uses: softprops/action-gh-release@v1
        with:
          files: dist/*.exe
        env:
          GITHUB_TOKEN: ${{ secrets.GH_TOKEN }}
