name: Build Electron App

on:
  push:
    branches: [ main ]

jobs:
  build:
    runs-on: windows-latest

    steps:
      # Step 1 — Checkout repo
      - uses: actions/checkout@v4

      # Step 2 — Setup Node.js
      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 20

      # Step 3 — Install dependencies
      - name: Install dependencies
        run: npm install

      # Step 4 — Build Electron app
      - name: Build app
        run: npm run dist

      # Step 5 — Upload the built .exe as artifact
      - name: Upload Electron Build
        uses: actions/upload-artifact@v4
        with:
          name: OpenArt-Windows
          path: dist/*.exe
